### ISSUE TITLE
SUSE Cloud 5 and Beyond

### ISSUE THREAD

**Issue by darksheer** [SUSE-Cloud/suse-cloud-vagrant#18]
Hi Adam,

I have put together a Vagrant Box that leverages @cseader's SUSE Cloud appliance, so I wanted to check and see if there is any interest in continuing the work you have done this far in the project for building out test/demo environments via Vagrant.

**Comment by aspiers** [comment]
Hi Vincent,

We already have a process for automatically building Vagrant boxes for Cloud 5 and 6 in our Internal Build Service instance.  It needs a bit of polish, but we have a hard deadline to do this in time for SUSEcon (and ideally even Tokyo the week before that), so it will happen soon.

**Comment by darksheer** [comment]
Awesome, glad I asked before putting too much effort into it. 

I look forward to seeing it @SUSECon
